name: Docker Build with Self-hosted Runner
on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build -t frontend-only-app .
        
      - name: Run container for testing
        run: docker run -d -p 3006:3000 --name frontend-app frontend-only-app
        
      - name: Wait for container to be ready
        run: |
          echo "Waiting for application to start..."
          sleep 5
          
  test:
    needs: build-and-run
    runs-on: self-hosted
    steps:
      - name: Check if service is accessible (200 status code)
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3006)
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "Service is accessible with status code 200"
          else
            echo "Service check failed. Status code: $HTTP_STATUS"
            exit 1
          fi
          
  cleanup:
    needs: [build-and-run, test]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Stop and remove container
        run: |
          echo "Cleaning up container..."
          docker stop frontend-app || true
          docker rm frontend-app || true
          echo "Container removed successfully"
