name: Docker Build with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t frontend-only-app .

    - name: Run container
      run: docker run -d -p 3006:3000 --name frontend-app frontend-only-app

    - name: Wait for app (max 10 tries)
      run: |
        for i in {1..10}; do
          code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3006 || echo 000)
          [ "$code" = "200" ] && echo "App OK and returned HTTP 200!" && exit 0
          echo "Try $i: Got $code. Retrying..." && sleep 3
        done
        echo "App did not respond with 200." && docker logs frontend-app && exit 1

    - name: Show logs if failed
      if: failure()
      run: docker logs frontend-app

    - name: Clean up
      run: docker rm -f frontend-app
