name: Docker Build with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t frontend-only-app .

    - name: Run Docker Container
      run: docker run -d -p 3006:3000 --name running-frontend-app-v6 frontend-only-app

    - name: Wait and check if app is running (HTTP 200)
      run: |
        echo "Waiting for app to be ready..."
        for i in {1..10}; do
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --fail http://localhost:3006 || echo "000")
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "App is running and returned HTTP 200!"
            break
          else
            echo "Attempt $i: Got HTTP $STATUS_CODE, retrying in 3s..."
            sleep 3
          fi

          if [ "$i" -eq 10 ]; then
            echo "App failed to respond with HTTP 200 after 10 attempts."
            docker logs running-frontend-app-v4
            exit 1
          fi
        done

    - name: Show container logs (for debugging)
      if: failure()
      run: docker logs running-frontend-app-v6

    - name: Stop and remove Docker container
      run: |
        docker stop running-frontend-app-v6
        docker rm running-frontend-app-v6


