name: Docker Build with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t frontend-only-app .

    - name: Run Docker Container
      run: docker run -d -p 3004:3000 --name running-frontend-app-v4 frontend-only-app

    - name: Test if app is running and returning status 200
      run: |
        # Wait for the app to be ready by retrying a few times
        for i in {1..10}; do
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3004)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "App is running and returned HTTP 200!"
            break
          else
            echo "Attempt $i: App not ready yet (HTTP $STATUS_CODE), retrying..."
            sleep 1
          fi
          if [ "$i" -eq 10 ]; then
            echo "App failed to respond with HTTP 200 after 10 attempts."
            exit 1
          fi
        done

    - name: Stop and remove Docker container
      run: |
        docker stop running-frontend-app-v4
        docker rm running-frontend-app-v4

