name: Docker Build with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t frontend-only-app .

    - name: Run Docker Container
      run: docker run -d -p 3001:3000 --name running-frontend-app-v2 frontend-only-app

    - name: Wait for container to initialize
      run: sleep 5

    - name: Test if app is running using curl
      run: |
        if curl -s http://localhost:3000 > /dev/null; then
          echo "App is running successfully!"
        else
          echo "App failed to run."
          exit 1
        fi
